print("Data Extraction From Different Type Of Source")
print("Data Cleaning")
print("Data Tranformation done!!!")
print("Data Exploration done!!!!")
print ("Data analysis done!! and Data Visulization!!")
print("data reporting add on!!!")